# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dKumaraswamy <- function(x, a, b) {
    .Call('_QAR_dKumaraswamy', PACKAGE = 'QAR', x, a, b)
}

dKumaraswamyCube <- function(x, a, b) {
    .Call('_QAR_dKumaraswamyCube', PACKAGE = 'QAR', x, a, b)
}

pKumaraswamy <- function(q, a, b) {
    .Call('_QAR_pKumaraswamy', PACKAGE = 'QAR', q, a, b)
}

qKumaraswamy <- function(p, a, b) {
    .Call('_QAR_qKumaraswamy', PACKAGE = 'QAR', p, a, b)
}

logdnorm <- function(x, sd) {
    .Call('_QAR_logdnorm', PACKAGE = 'QAR', x, sd)
}

logdmvnorm <- function(x, mu, sigma2, Rinv, n) {
    .Call('_QAR_logdmvnorm', PACKAGE = 'QAR', x, mu, sigma2, Rinv, n)
}

MuSigmaUpdate <- function(x, mu, Sigma, n) {
    .Call('_QAR_MuSigmaUpdate', PACKAGE = 'QAR', x, mu, Sigma, n)
}

logitInv <- function(x, a, b) {
    .Call('_QAR_logitInv', PACKAGE = 'QAR', x, a, b)
}

logitInvVec <- function(x, a, b) {
    .Call('_QAR_logitInvVec', PACKAGE = 'QAR', x, a, b)
}

fQAR1K1 <- function(x, y1, y2, a1, b1, a2, b2) {
    .Call('_QAR_fQAR1K1', PACKAGE = 'QAR', x, y1, y2, a1, b1, a2, b2)
}

brentQAR1K1 <- function(y1, y2, a1, b1, a2, b2, tol) {
    .Call('_QAR_brentQAR1K1', PACKAGE = 'QAR', y1, y2, a1, b1, a2, b2, tol)
}

logLikelihoodQAR1K1 <- function(T, L, Y, a1, b1, a2, b2, tol) {
    .Call('_QAR_logLikelihoodQAR1K1', PACKAGE = 'QAR', T, L, Y, a1, b1, a2, b2, tol)
}

logfallQAR1K1 <- function(T, L, x, Y, prior, tol) {
    .Call('_QAR_logfallQAR1K1', PACKAGE = 'QAR', T, L, x, Y, prior, tol)
}

rwBmetropolisQAR1K1 <- function(x, sd, T, L, Y, prior, tol) {
    .Call('_QAR_rwBmetropolisQAR1K1', PACKAGE = 'QAR', x, sd, T, L, Y, prior, tol)
}

fQAR1K2 <- function(x, y1, y2, a1, b1, a2, b2, a3, b3, a4, b4, pi1, pi2) {
    .Call('_QAR_fQAR1K2', PACKAGE = 'QAR', x, y1, y2, a1, b1, a2, b2, a3, b3, a4, b4, pi1, pi2)
}

brentQAR1K2 <- function(y1, y2, a1, b1, a2, b2, a3, b3, a4, b4, pi1, pi2, tol) {
    .Call('_QAR_brentQAR1K2', PACKAGE = 'QAR', y1, y2, a1, b1, a2, b2, a3, b3, a4, b4, pi1, pi2, tol)
}

logLikelihoodQAR1K2 <- function(T, L, Y, a1, b1, a2, b2, a3, b3, a4, b4, pi1, pi2, tol) {
    .Call('_QAR_logLikelihoodQAR1K2', PACKAGE = 'QAR', T, L, Y, a1, b1, a2, b2, a3, b3, a4, b4, pi1, pi2, tol)
}

logfallQAR1K2 <- function(T, L, x, Y, prior, tol) {
    .Call('_QAR_logfallQAR1K2', PACKAGE = 'QAR', T, L, x, Y, prior, tol)
}

rwBmetropolisQAR1K2 <- function(x, sd, T, L, Y, prior, tol) {
    .Call('_QAR_rwBmetropolisQAR1K2', PACKAGE = 'QAR', x, sd, T, L, Y, prior, tol)
}

fQAR1K <- function(x, y1, y2, K, ab, lambda, lambda1K, lambda2K) {
    .Call('_QAR_fQAR1K', PACKAGE = 'QAR', x, y1, y2, K, ab, lambda, lambda1K, lambda2K)
}

brentQAR1K <- function(y1, y2, K, ab, lambda, lambda1K, lambda2K, tol) {
    .Call('_QAR_brentQAR1K', PACKAGE = 'QAR', y1, y2, K, ab, lambda, lambda1K, lambda2K, tol)
}

logLikelihoodQAR1K <- function(T, L, Y, K, ab, lambda, tol) {
    .Call('_QAR_logLikelihoodQAR1K', PACKAGE = 'QAR', T, L, Y, K, ab, lambda, tol)
}

logfallQAR1K <- function(T, L, x, Y, K, ab, prior, tol) {
    .Call('_QAR_logfallQAR1K', PACKAGE = 'QAR', T, L, x, Y, K, ab, prior, tol)
}

rwBmetropolisQAR1K <- function(x, sd, T, L, Y, K, ab, prior, tol) {
    .Call('_QAR_rwBmetropolisQAR1K', PACKAGE = 'QAR', x, sd, T, L, Y, K, ab, prior, tol)
}

fQAR2K1 <- function(x, y1, y2, y3, a1, b1, a2, b2, a3, b3, pi) {
    .Call('_QAR_fQAR2K1', PACKAGE = 'QAR', x, y1, y2, y3, a1, b1, a2, b2, a3, b3, pi)
}

brentQAR2K1 <- function(y1, y2, y3, a1, b1, a2, b2, a3, b3, pi, tol) {
    .Call('_QAR_brentQAR2K1', PACKAGE = 'QAR', y1, y2, y3, a1, b1, a2, b2, a3, b3, pi, tol)
}

logLikelihoodQAR2K1 <- function(T, L, Y, a1, b1, a2, b2, a3, b3, pi, tol) {
    .Call('_QAR_logLikelihoodQAR2K1', PACKAGE = 'QAR', T, L, Y, a1, b1, a2, b2, a3, b3, pi, tol)
}

logfallQAR2K1 <- function(T, L, x, Y, prior, tol) {
    .Call('_QAR_logfallQAR2K1', PACKAGE = 'QAR', T, L, x, Y, prior, tol)
}

rwBmetropolisQAR2K1 <- function(x, sd, T, L, Y, prior, tol) {
    .Call('_QAR_rwBmetropolisQAR2K1', PACKAGE = 'QAR', x, sd, T, L, Y, prior, tol)
}

logLikelihoodMQAR1K1 <- function(T, L, Y, a1, b1, a2, b2, a3, b3, a4, b4, rho, tol) {
    .Call('_QAR_logLikelihoodMQAR1K1', PACKAGE = 'QAR', T, L, Y, a1, b1, a2, b2, a3, b3, a4, b4, rho, tol)
}

logfallMQAR1K1 <- function(T, L, x, Y, prior, tol) {
    .Call('_QAR_logfallMQAR1K1', PACKAGE = 'QAR', T, L, x, Y, prior, tol)
}

rwBmetropolisMQAR1K1 <- function(x, sd, T, L, Y, prior, tol) {
    .Call('_QAR_rwBmetropolisMQAR1K1', PACKAGE = 'QAR', x, sd, T, L, Y, prior, tol)
}

logLikelihoodSQAR1K1 <- function(T, L, n, Y, a1, b1, a2, b2, gamma, RPhi, I, tol) {
    .Call('_QAR_logLikelihoodSQAR1K1', PACKAGE = 'QAR', T, L, n, Y, a1, b1, a2, b2, gamma, RPhi, I, tol)
}

logfallSQAR1K1 <- function(T, L, n, x, Y, RPhi, I, prior, tol) {
    .Call('_QAR_logfallSQAR1K1', PACKAGE = 'QAR', T, L, n, x, Y, RPhi, I, prior, tol)
}

rwBmetropolisSQAR1K1 <- function(x, sd, T, L, n, Y, RPhi, I, prior, tol) {
    .Call('_QAR_rwBmetropolisSQAR1K1', PACKAGE = 'QAR', x, sd, T, L, n, Y, RPhi, I, prior, tol)
}

logLikelihoodSGPQAR1K1 <- function(T, L, n, Y, gamma, GP, RPhi, I, tol) {
    .Call('_QAR_logLikelihoodSGPQAR1K1', PACKAGE = 'QAR', T, L, n, Y, gamma, GP, RPhi, I, tol)
}

logfallSGPQAR1K1 <- function(T, L, n, x, Y, RPhi, Rinv, I, prior, tol) {
    .Call('_QAR_logfallSGPQAR1K1', PACKAGE = 'QAR', T, L, n, x, Y, RPhi, Rinv, I, prior, tol)
}

rwBmetropolisSGPQAR1K1 <- function(x, sd, T, L, n, Y, RPhi, Rinv, I, prior, tol) {
    .Call('_QAR_rwBmetropolisSGPQAR1K1', PACKAGE = 'QAR', x, sd, T, L, n, Y, RPhi, Rinv, I, prior, tol)
}

fKX2006 <- function(x, y1, y2, mu, sigma, gamma0, gamma1) {
    .Call('_QAR_fKX2006', PACKAGE = 'QAR', x, y1, y2, mu, sigma, gamma0, gamma1)
}

brentKX2006 <- function(y1, y2, mu, sigma, gamma0, gamma1, tol) {
    .Call('_QAR_brentKX2006', PACKAGE = 'QAR', y1, y2, mu, sigma, gamma0, gamma1, tol)
}

logLikelihoodKX2006 <- function(T, L, Y, mu, sigma, gamma0, gamma1, tol) {
    .Call('_QAR_logLikelihoodKX2006', PACKAGE = 'QAR', T, L, Y, mu, sigma, gamma0, gamma1, tol)
}

logfallKX2006 <- function(T, L, x, Y, prior, tol) {
    .Call('_QAR_logfallKX2006', PACKAGE = 'QAR', T, L, x, Y, prior, tol)
}

rwBmetropolisKX2006 <- function(x, sd, T, L, Y, prior, tol) {
    .Call('_QAR_rwBmetropolisKX2006', PACKAGE = 'QAR', x, sd, T, L, Y, prior, tol)
}

